# -*- coding: utf-8 -*-
"""password_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VblNbWs6ReFn3wEkO0eJSzUHMO4d_9Fk
"""

import random
import string

def analyze_password(password):

    score = 0
    missing = []

    length = len(password)

    if length >= 16:
        score += 3
    elif length >= 12:
        score += 2
    elif length >= 8:
        score += 1
    else:
        missing.append("too short")

    has_upper = False
    has_lower = False
    has_digit = False
    has_special = False

    repeat_ok = True
    count = 1

    for i in range(len(password)):

        char = password[i]

        if char.isupper():
            has_upper = True

        if char.islower():
            has_lower = True

        if char.isdigit():
            has_digit = True

        if char in "!@#$%^&*":
            has_special = True

        if i > 0:
            if password[i] == password[i-1]:
                count += 1
                if count > 2:
                    repeat_ok = False
            else:
                count = 1

    if has_upper:
        score += 1
    else:
        missing.append("uppercase")

    if has_lower:
        score += 1
    else:
        missing.append("lowercase")

    if has_digit:
        score += 1
    else:
        missing.append("digit")

    if has_special:
        score += 1
    else:
        missing.append("special char")

    if repeat_ok:
        score += 1

    return score, missing


def rating(score):

    if score <= 2:
        return "Weak"
    elif score <= 4:
        return "Medium"
    elif score <= 6:
        return "Strong"
    else:
        return "Very Strong"


def generate_password(length):

    chars = string.ascii_letters + string.digits + string.punctuation

    password = ""

    for i in range(length):
        password += random.choice(chars)

    return password


while True:

    password = input("Enter password: ")

    score, missing = analyze_password(password)

    print(f"Strength: {score}/7 ({rating(score)})")

    if missing:
        print("Missing:", ", ".join(missing))

    if score >= 5:
        print("Password accepted!")
        break

    print("Try again...\n")


length = int(input("\nEnter length for generated password: "))

generated = generate_password(length)

print("Generated Password:", generated)

score, missing = analyze_password(generated)

print(f"Generated Password Strength: {score}/7 ({rating(score)})")