# -*- coding: utf-8 -*-
"""transaction_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8xpLxC5XFgGtyN2bhibMsfnGFwPmRs8
"""

transactions = []
types = []
categories = []

total_credit = 0
total_debit = 0

print("Enter transactions (type 'done' to stop)")

while True:

    amount_input = input("Enter amount: ")

    if amount_input.lower() == "done":
        break

    amount = float(amount_input)

    t_type = input("Type (credit/debit): ").lower()
    category = input("Category (food/travel/bills/other): ").lower()

    transactions.append(amount)
    types.append(t_type)
    categories.append(category)

    if amount > 10000:
        print("⚠ High value transaction detected!")

    if t_type == "credit":
        total_credit += amount
    else:
        total_debit += amount


net_balance = total_credit - total_debit
count = len(transactions)

highest = max(transactions) if transactions else 0
average = sum(transactions) / count if count > 0 else 0


print("\nBar Chart (Last 10 Transactions)")

last_transactions = transactions[-10:]

for amount in last_transactions:

    stars = int(amount / 1000)

    print(f"{amount} | ", end="")

    for i in range(stars):
        print("*", end="")

    print()


category_summary = {}

for i in range(len(categories)):

    cat = categories[i]
    amt = transactions[i]

    if cat not in category_summary:
        category_summary[cat] = 0

    category_summary[cat] += amt


print("\n----- Summary -----")

print("Total Transactions:", count)
print("Total Credits:", total_credit)
print("Total Debits:", total_debit)
print("Net Balance:", net_balance)
print("Highest Transaction:", highest)
print("Average Transaction:", average)

print("\nSpending Breakdown by Category")

for cat, amt in category_summary.items():
    print(cat, ":", amt)